services:
  db:
    image: postgres:17-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todolist_nextjs
    networks:
      - local
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    

volumes:
  pgdata:

networks:
  local: 
    external: true