import { env } from '@/lib/env';

const POSTGRES_USER = env.POSTGRES_USER;
const POSTGRES_PASSWORD = env.POSTGRES_PASSWORD;
const POSTGRES_HOST = env.POSTGRES_HOST;
const POSTGRES_PORT = env.POSTGRES_PORT;
const POSTGRES_DATABASE = env.POSTGRES_DATABASE;

export const DATABASE_URL = `postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DATABASE}`;